### ISSUE TITLE
How to use the cell formatter to return a Svelte component?

### ISSUE THREAD

**Issue by atresnjo** [iamyuu/gridjs-svelte#2]
Basically something like https://gridjs.io/docs/examples/react-cells

Thanks! :)

**Comment by iamyuu** [comment]
"Grid.js uses Preact to render the elements and that means that you can take advantage of Preact's **Virtual DOM** and render complex cells."

And Svelte approach is using the compiler and uses real DOM, instead of using virtual DOM. So I think, you can't use Svelte component to handle this.

But you can use [`html`](http://gridjs.io/docs/examples/html-cells), check out [my repl](https://svelte.dev/repl/3c6d68ee5793465fb19b16b3d6831d57).

**Comment by atresnjo** [comment]
Hey, thanks for the reply!

```svelte
html
```
Works fine if you just want to return the cell itself, but not a svelte component. There must be a way to create a Svelte component on fly, pass the props and then return the built html. I'll try to play around with it, thanks so far! 👍

**Comment by benwoodward** [comment]
+1.

Would be great to be able to use a Svelte component so that changes to the site theme are automatically reflected in gridjs instances.

**Comment by vince-xopolis** [comment]
I would like to use svelte components with gridjs so that I can use bootstrap icons with my data.  It would be very useful to use something like html from gridjs to do it.

**Comment by iamyuu** [comment]
Hey there! On v2 I already added plugins to wrapping the svelte component, so now we can to svelte component to render the cell. Check out the [example](https://svelte.dev/repl/e3247cb80c344f95b1fdd2853006f159).

Note: (currently!) when we use plugin we not receive the data, I don't why but I think it's might bug on Grid.js
